apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-usage-server.fullname" . }}
  labels:
    {{- include "api-usage-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
      ssl:
        mode: {{ .Values.global.database.ssl.mode }}
        rootCert: {{ .Values.global.database.ssl.rootCert }}
      createDatabase: {{ .Values.global.database.createDatabase }}
      originalDatabase: {{ .Values.global.database.originalDatabase }}
