apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-usage-server.fullname" . }}
  labels:
    {{- include "api-usage-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    adminGrpcPort: {{ .Values.adminGrpcPort }}
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    cleaner:
      pollInterval: {{ .Values.cleaner.pollInterval }}
      retentionPeriod: {{ .Values.cleaner.retentionPeriod }}
    database:
      host: {{ required "global.database.host is required" .Values.global.database.host }}
      port: {{ required "global.database.host is required" .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ required "global.database.username is required" .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
      ssl:
        mode: {{ .Values.global.database.ssl.mode }}
        rootCert: {{ .Values.global.database.ssl.rootCert }}
      createDatabase: {{ .Values.global.database.createDatabase }}
      originalDatabase: {{ .Values.global.database.originalDatabase }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
