apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-usage-server.fullname" . }}-http
  labels:
    {{- include "api-usage-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - {{- if .Values.global.ingress.host }}
    host: {{ .Values.global.ingress.host }}
    {{- end }}
    http:
      paths:
      - path: /v1/api_usages
        pathType: Prefix
        backend:
          service:
            name: {{ include "api-usage-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
      - path: /v1/api-usage
        pathType: Prefix
        backend:
          service:
            name: {{ include "api-usage-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
