apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-usage-server.fullname" . }}-admin-grpc
  labels:
    {{- include "api-usage-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.adminGrpcPort }}
    targetPort: admin-grpc
    protocol: TCP
    name: admin-grpc
  selector:
    {{- include "api-usage-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-usage-server.fullname" . }}-internal-grpc
  labels:
    {{- include "api-usage-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.internalGrpcPort }}
    targetPort: internal-grpc
    protocol: TCP
    name: internal-grpc
  selector:
    {{- include "api-usage-server.selectorLabels" . | nindent 4 }}
