// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectionInternalServiceClient is the client API for CollectionInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionInternalServiceClient interface {
	CollectUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*CollectUsageResponse, error)
}

type collectionInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionInternalServiceClient(cc grpc.ClientConnInterface) CollectionInternalServiceClient {
	return &collectionInternalServiceClient{cc}
}

func (c *collectionInternalServiceClient) CollectUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*CollectUsageResponse, error) {
	out := new(CollectUsageResponse)
	err := c.cc.Invoke(ctx, "/llmariner.apiusage.server.v1.CollectionInternalService/CollectUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionInternalServiceServer is the server API for CollectionInternalService service.
// All implementations must embed UnimplementedCollectionInternalServiceServer
// for forward compatibility
type CollectionInternalServiceServer interface {
	CollectUsage(context.Context, *CollectUsageRequest) (*CollectUsageResponse, error)
	mustEmbedUnimplementedCollectionInternalServiceServer()
}

// UnimplementedCollectionInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectionInternalServiceServer struct {
}

func (UnimplementedCollectionInternalServiceServer) CollectUsage(context.Context, *CollectUsageRequest) (*CollectUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectUsage not implemented")
}
func (UnimplementedCollectionInternalServiceServer) mustEmbedUnimplementedCollectionInternalServiceServer() {
}

// UnsafeCollectionInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionInternalServiceServer will
// result in compilation errors.
type UnsafeCollectionInternalServiceServer interface {
	mustEmbedUnimplementedCollectionInternalServiceServer()
}

func RegisterCollectionInternalServiceServer(s grpc.ServiceRegistrar, srv CollectionInternalServiceServer) {
	s.RegisterService(&CollectionInternalService_ServiceDesc, srv)
}

func _CollectionInternalService_CollectUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionInternalServiceServer).CollectUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.apiusage.server.v1.CollectionInternalService/CollectUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionInternalServiceServer).CollectUsage(ctx, req.(*CollectUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionInternalService_ServiceDesc is the grpc.ServiceDesc for CollectionInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.apiusage.server.v1.CollectionInternalService",
	HandlerType: (*CollectionInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectUsage",
			Handler:    _CollectionInternalService_CollectUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/collector_server.proto",
}
