global:
  database:
    host:
    port:
    username:
    ssl:
      mode:
      rootCert:
    createDatabase:
    originalDatabase:

  databaseSecret:
    name:
    key:

database:
  database: api_usage

internalGrpcPort: 8082

replicaCount: 1

image:
  repository: public.ecr.aws/cloudnatix/llmariner/api-usage-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  grpc:
    port: 8082
  initialDelaySeconds: 3
  failureThreshold: 5

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
