apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-usage-cleaner.fullname" . }}
  labels:
    {{- include "api-usage-cleaner.labels" . | nindent 4 }}
data:
  config.yaml: |
    pollInterval: {{ .Values.pollInterval }}
    retentionPeriod: {{ .Values.retentionPeriod }}
    database:
      host: {{ required "global.database.host is required" .Values.global.database.host }}
      port: {{ required "global.database.port is required" .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ required "global.database.username is required" .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
      ssl:
        mode: {{ .Values.global.database.ssl.mode }}
        rootCert: {{ .Values.global.database.ssl.rootCert }}
      createDatabase: {{ .Values.global.database.createDatabase }}
      originalDatabase: {{ .Values.global.database.originalDatabase }}
