apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-usage-cleaner.fullname" . }}
  labels:
    {{- include "api-usage-cleaner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-usage-cleaner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-usage-cleaner.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: api-usage-cleaner
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.databaseSecret.name }}
              key: {{ .Values.global.databaseSecret.key }}
        {{- with .Values.apiUsageCleaner }}
          {{- with .env }}
        {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .envFrom }}
        envFrom:
        {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "api-usage-cleaner.fullname" . }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
